name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - apostasie
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you running this on?
      multiple: false
      options:
        - macOS
        - Debian
        - Alpine
        - Other Linux
  - type: checkboxes
    id: container
    attributes:
      label: Container
      description: Check this if you are running inside a container
      options:
        - label: I am running this inside a container
          required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A bug happened!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
